var multilingual = {
    "English": {
        FlagshipVersion: "Flagship version",
        SubmitTime: "Submit Time",
        PaperNumber: "Words",
        OverallSimilarity: "Overall Similarity",
        DetailReport: "Report",
        TextProofreading: "Proofreading",
        ComprehensiveAssessment: "Assessment",
        ViewOriginal: "Original",
        UseHelp: "Help",
        Download: "Download",
        DownloadOriginal: "Download Original",
        DownloadHTM: "Download Offline Report",
        DownloadPDF: "Download the PDF version",
        DownloadWord: "Download the Word version",
        SupportJavaScript: "JavaScript is forbidden!",
        LoadingReport: "Loading Report...",
        Similarity: "Similarity",
        SimilarityTip: "Please expand right side for more information",
        AditionalSentences: "Aditional sentences",
        BlankPage: "[This page is blank, please view the next page]",
        SwitchMode: "Switch Mode",
        DirectoryNavigation: "Document Outline",
        WebpageNavigation: "Page Navigation",
        ModifyDocument: "Modify Document",
        AuxiliaryLine: "Colorweakness Mode",
        PreviousPage: "Previous Page",
        NextPage: "Next Page",
        Enter: "Enter Page Number",
        Jump: "Go",
        Scale: "Reading Tools",
        Zoom: "Zoom",
        ZoomOut: "Zoom Out",
        ScalingRatio: "Scaling Ratio",
        FitWidth: "Fitting Width",
        SuitableHeight: "Fitting Height",
        OriginalSize: "Initial Size",
        WordMode: 'Switch to Microsoft Word Mode?',
        TextMode: 'Switch to Text Mode?',
        Confirm: "Confirm",
        Cancel: "Cancel",
        EmptyDirectoryNavigation: "Document Outline is Null",
        CollapseAll: "Fold All",
        ExpandAll: "Unfold All",
        EmptyWebPageNavigation: "Page Navigation is Null",
        UseLine: 'Switch to Colorweakness Mode?',
        CancelLine: 'Switch to Normal Mode?',
        UseAuxiliaryLine: "Colorweakness Mode",
        CancelAuxiliaryLine: "Normal Mode",
        ModifyParagraph: "Modify Paragraph",
        Modify: "Modify",
        TemporarySave: "Temporary Save",
        CancelSave: "Cancel Save",
        ModifyTip: 'After modify current paragraph,clicking "Temporary Save" to view  the latest contents in the modify docunment page',
        DocumentTip: 'In order to avoide the affection by systemic environment,please save your modified paper as soon as possible',
        AlertSuccess: "These contents which turn into green has been temprarily saved in your paper.",
        SupportBrowser: "Your broweser is not supported the paragraph editing function,please use other browser!",
        FirstPage: "First Page",
        LastPage: "Last Page",
        PageNumber: "Page Number", 
        Page: "Page", 
        NumberOfPages: "Number Of Pages",
        Loading: "Loading...",
        DifferentSimilarityTip: "Different colors represents different simlilarity the degrees",
        Red: "Red",
        Orange: "Orange",
        Black: "Black",
        Green: "Green",
        SevereSimilarity: "Over 70% similar(highly similar,please modify comprehensively)",
        SlightlySimilar: "40%~70% similar(lightly similar,please modify according to the circunstances)",
        Qualified: "Qualified",
        ViewDetailSentence: 'Please click "Red" and "Orange" pards to see the detecting detail',
        SentenceSimilarityTip: "Sentence Similarity",
        YourSentence: "Your Sentence",
        Composite: "Composite",
        Library: "Local",
        Internet: "Internet",
        SelfBuiltLibrary: "Self-built Library",
        SimilarSentences: "Similar Sentences",
        SimilarOriginalFragment: "Similar to the original fragment",
        Source: "Source",
        Journal: "Journal",
        Dissertation: "Dissertation",
        AcademicConferences: "Academic Conferences",
        BookData: "Book Data",
        University: "University",
        Title: "Title",
        Author: "Author",
        Periodical: "Periodical",
        Issue: "Issue",
        PeriodicalColumn: "Periodical Column",
        ClassificationNumber: "Classification Number",
        Funding: "Funding",
        Abstract: "Abstract",
        PublicationDate: "Publication Date",
        PeriodicalLevel: "Periodical Level",
        ISSN: "ISSN",
        DegreeAwarded: "Degree Awarded",
        DegreeGrantingUnit: "Degree Awarded Institution",
        DegreeYear: "Degree Year",
        Major: "Major",
        TeacherName: "Teacher Name",
        Conference: "Conference",
        Organizer: "Organizer",
        ConferenceDate: "Conference Date",
        ConferenceLocation: "Conference Location",
        Chapter: "Chapter",
        Publisher: "Publisher",
        ISBN: "ISBN",
        Provenance: "Origin",
        OpenSearch: "OpenSearch",
        Length: "Length",
        UploadTime: "Upload Time",
        Keyword: "Keyword",
        BackTop: "Back Top",
        BasicInformation: "Basic Information",
        PaperTitle: "Title",
        PaperTime: "Time",
        LocalLibrarySimilarity: "Similarity degrees in local database",
        JournalLibrarySimilarity: "Similarity degrees in journal database",
        DegreeLibrarySimilarity: "Similarity degrees in degree database",
        MeetingSimilarity: "Similarity degrees in meeting database",
        LibrarySimilarity: "Similarity degrees in library database",
        InternetSimilarity: "Similarity degrees in internet database",
        SelfbuiltSimilarity: "Self-built Similarity",
        SimilarityCalculationFormula: "Similarity Calculation Formula",
        Formula: "(Sentence1 similarity + Sentence2 similarity........ / n)",
        SimilarityRange: "Sentence similarity scale from 0.0~1.0",
        SimilarityRangeDetail: "Green sentence reprensent similarity-free",
        SimilarityDistribution: "Sentences similarity distribution",
        PointDistributionDiagram: "Unqualificted sentences dotted distribution map",
        Sentence: "Sentence",
        LocalLibrariesTitle: "Similar resources on local database",
        localTip: "Highil similar resources on local database has not been founded.",
        Details: "Details",
        PutAway: "Fold",
        ViewMore: "View More",
        InternetSimilarResources: "Similar resources on internet",
        InternetTip: "Highil similar resources on internet has not been founded.",
        PaperFooter: "This report is powerd by paperpass.net similarity detecting system",
        Copyright: "Copyright",
        LoadingOriginal: "Loading Original Text...",
        Aditional: "Aditional sentences",
        Word: "Report.Word",
        Text: "Report.Text",
    },
    "Deutsch": {
        FlagshipVersion: "Ultimative Edition",
        SubmitTime: "Abgabetermin",
        PaperNumber: "Anzahl der Zeichen",
        OverallSimilarity: "Gesamtähnlichkeit",
        DetailReport: "Bericht",
        TextProofreading: "Korrektur",
        ComprehensiveAssessment: "Bewertung",
        ViewOriginal: "Originaltext",
        UseHelp: "Hilfe",
        Download: "Herunterladen",
        DownloadOriginal: "Original herunterladen",
        DownloadHTM: "Offline-Bericht herunterladen",
        DownloadPDF: "Laden Sie die PDF-Version herunter",
        DownloadWord: "Laden Sie die Word-Version herunter",
        SupportJavaScript: "JavaScript auf Ihrem aktuellen Browser ist deaktiviert! ! !",
        LoadingReport: "Bericht wird geladen, bitte warten...",
        Similarity: "Ähnlichkeit",
        SimilarityTip: "Erweitern Sie bitte die rechte Seite, um den ausführlichen Bericht anzuzeigen",
        AditionalSentences: "Ergänzungsseite für ähnliche Sätze",
        BlankPage: "[Diese Seite ist leer, bitte sehen Sie sich die nächste Seite an]",
        SwitchMode: "Modus wechseln",
        DirectoryNavigation: "Verzeichnisnavigation",
        WebpageNavigation: "Website-Navigator",
        ModifyDocument: "Dokument ändern",
        AuxiliaryLine: "Hilfslinie",
        PreviousPage: "Vorherige Seite",
        NextPage: "Nächste Seite",
        Enter: "Seitenzahl eingeben",
        Jump: "Springen",
        Scale: "Zoomen",
        Zoom: "Reinzoomen",
        ZoomOut: "Rauszoomen",
        ScalingRatio: "Zoomverhältnis",
        FitWidth: "Geeignete Breite",
        SuitableHeight: "Geeignete Höhe",
        OriginalSize: "Originalgröße",
        WordMode: 'Möchten Sie wirklich in den "Word-Modus" wechseln?',
        TextMode: 'Möchten Sie wirklich in den "Textmodus" wechseln?',
        Confirm: "Bestätigen",
        Cancel: "Abbrechen",
        EmptyDirectoryNavigation: "Verzeichnisnavigation ist leer",
        CollapseAll: "Alles einblenden",
        ExpandAll: "Alles ausblenden",
        EmptyWebPageNavigation: "Seitennavigation ist leer",
        UseLine: '"Hilfslinie verwenden" bestätigen?',
        CancelLine: '"Hilfslinie abbrechen" bestätigen?',
        UseAuxiliaryLine: "Hilfslinien verwenden",
        CancelAuxiliaryLine: "Hilfslinie abbrechen",
        ModifyParagraph: "Absatzänderung",
        Modify: "Überarbeiten",
        TemporarySave: "Temporär sichern",
        CancelSave: "Sichern abbrechen",
        ModifyTip: 'Hinweis: Nachdem Sie diesen Absatz geändert haben, klicken Sie auf "temporär sichern", der geänderte Inhalt kann auf der Seite "Dokument ändern" angezeigt werden.',
        DocumentTip: 'Diese Funktion wird von der Systemumgebung beeinflusst, bitte speichern Sie die überarbeiteten Abteile so schnell wie möglich in Ihrem Artikel.',
        AlertSuccess: "Dies ist der  temporär gespeicherte Inhalt wird, nachdem Sie den Bericht geändert haben. Der bearbeitete Teil wird grün markiert.",
        SupportBrowser: 'Ihr aktueller Browser unterstützt keine Absatzbearbeitung, bitte verwenden Sie einen anderen Browser! ! !',
        FirstPage: "Hauptseite",
        LastPage: "Endseite",
        PageNumber: "Seitennummer", 
        Page: "Seite", 
        NumberOfPages: "Seitenzahl",
        Loading: "Wird geladen...",
        DifferentSimilarityTip: "Unterschiedliche Satzfarben deuten auf unterschiedliche Ähnlichkeiten",
        Red: "Rot",
        Orange: "Orange",
        Black: "Schwarz",
        Green: "Grün",
        SevereSimilarity: "Ähnlichkeit mehr als 70% (starke Ähnlichkeit, komplett Überarbeiten erförderlich)",
        SlightlySimilar: "Ähnlichkeit 40%-70% (etwas ähnlich, entsprechendes Ändern benötigt)",
        Qualified: "qualifiziert",
        ViewDetailSentence: 'Wenn Sie die ausführlichen Testergebnisse von Sätzen einsehen möchten, klicken Sie bitte auf die "rot" und "orange" markierten Stellen',
        SentenceSimilarityTip: "Ähnlichkeit des Satzes",
        YourSentence: "Ihr satz",
        Composite: "Umfassend",
        Library: "Lokale",
        Internet: "Internet",
        SelfBuiltLibrary: "Selbstgebaute Bibliothek",
        SimilarSentences: "Ähnliche sätze",
        SimilarOriginalFragment: "Ähnliche originalfragmente",
        Source: "Quelle",
        Journal: "Fachzeitschriften",
        Dissertation: "These",
        AcademicConferences: "Akademisches seminar",
        BookData: "Buchdaten",
        University: "Vergleichsbibliothek der Universitäten",
        Title: "Titel",
        Author: "Autor",
        Periodical: "Zeitschrift",
        Issue: "Veröffentlichungsdatum",
        PeriodicalColumn: "Journalspalte",
        ClassificationNumber: "Klassifizierungsnummer",
        Funding: "Fondsprojekt",
        Abstract: "Zusammenfassung",
        PublicationDate: "Veröffentlichungsdatum",
        PeriodicalLevel: "Journalklassifizierung",
        ISSN: "ISSN",
        DegreeAwarded: "Vergabeeinheit",
        DegreeGrantingUnit: "Abschluss verliehen",
        DegreeYear: "Abschlussjahr",
        Major: "Hauptfach",
        TeacherName: "Name des Tutors",
        Conference: "Konferenzsname",
        Organizer: "Veranstalter",
        ConferenceDate: "Ziet der Konferenz",
        ConferenceLocation: "Adresse der Konferenz",
        Chapter: "Kapitel",
        Publisher: "Verlag",
        ISBN: "ISBN",
        Provenance: "Origin",
        OpenSearch: "OffenSuche",
        Length: "Länge",
        UploadTime: "Upload-Zeit",
        Keyword: "Schlüsselwörter",
        BackTop: "zurück zum Oben",
        BasicInformation: "Grundinformation",
        PaperTitle: "Thema",
        PaperTime: "Zeit",
        LocalLibrarySimilarity: "Ähnlichkeit mit der lokalen Bibliothek",
        JournalLibrarySimilarity: "Ähnlichkeit mit der Zeitschriftenbibliothek",
        DegreeLibrarySimilarity: "Ähnlichkeit mit der Abschlussbibliothek",
        MeetingSimilarity: "Ähnlichkeit mit der Konferenzbibliothek",
        LibrarySimilarity: "Ähnlichkeit mit der Buchbibliothek",
        InternetSimilarity: "Ähnlichkeit mit Internetdaten",
        SelfbuiltSimilarity: "Ähnlichkeit mit selbstgebauten Bibliotheken",
        SimilarityCalculationFormula: "Formel zur Ähnlichkeitsberechnung",
        Formula: "(Satz 1 Ähnlichkeit + Satz 2 Ähnlichkeit +…+Satz n Ähnlichkeit) / n",
        SimilarityRange: "Satzähnlichkeitsbereich 0.0～1.0",
        SimilarityRangeDetail: "Die Ähnlichkeit des grünen Satzes wird berechnet als 0",
        SimilarityDistribution: "Satzähnlichkeitsverteilung",
        PointDistributionDiagram: "Punktverteilungsdiagramm von unqualifizierten Sätzen",
        Sentence: "Satz",
        LocalLibrariesTitle: "Ähnliche Ressourcen der lokalen Bibliothek",
        LocalTip: "Keine Ressourcen mit hoher Ähnlichkeit mit der lokalen Bibliothek gefunden.",
        Details: "Einzelheiten",
        PutAway: "Ausblenden",
        ViewMore: "Einblenden",
        InternetSimilarResources: "Ähnliche Ressourcen im Internet",
        InternetTip: "Keine Ressource gefunden, die dem Internet sehr ähnlich ist",
        PaperFooter: "Der Prüfbericht wird vom PaperPass.Net-System zur Dokumentenähnlichkeitsprüfung erstellt",
        Copyright: "Urheberrechte",
        LoadingOriginal: "Originaltext wird geladen, bitte warten...",
        Aditional: "Ergänzungssatz",
        Word: "Ausführlicher Bericht.Word-Version",
        Text: "Ausführlicher Bericht.Klartextversion",
    },
    "Español": {
        FlagshipVersion: "Edición insignia",
        SubmitTime: "Fecha de presentación",
        PaperNumber: "Número de palabras del articulo",
        OverallSimilarity: "Similitud global",
        DetailReport: "Informe",
        TextProofreading: "Revisión",
        ComprehensiveAssessment: "Evaluación",
        ViewOriginal: "Texto original",
        UseHelp: "Ayuda",
        Download: "Descargar",
        DownloadOriginal: "Descargar original",
        DownloadHTM: "Descargar informe sin conexión",
        DownloadPDF: "Descarga la versión PDF",
        DownloadWord: "Descarga la versión WORD",
        SupportJavaScript: "¡¡¡El Javascript está desactivado en su navegador actual!!!",
        LoadingReport: "Está cargando el informe, por favor espere...",
        Similarity: "Similitud",
        SimilarityTip: "¡Para ver el informe detallado de la frase, amplíe a la derecha!",
        AditionalSentences: "Página complementaria de frases similares",
        BlankPage: "[Esta página está en blanco, por favor, consulte la siguiente página]",
        SwitchMode: "Cambio de modos",
        DirectoryNavigation: "Navegación por el índice",
        WebpageNavigation: "Navegación",
        ModifyDocument: "Modificar el documento",
        AuxiliaryLine: "Líneas auxiliares",
        PreviousPage: "Página anterior",
        NextPage: "Página siguiente",
        Enter: "Introduzca el número de página",
        Jump: "Saltar",
        Scale: "Zoom",
        Zoom: "Ampliar",
        ZoomOut: "Reducir",
        ScalingRatio: "Proporción del zoom",
        FitWidth: "Ajuste a la anchura",
        SuitableHeight: "Ajuste a la altura",
        OriginalSize: "Tamaño original",
        WordMode: '¿Quiere cambiar al "Modo Word"?',
        TextMode: '¿Desea cambiar al modo "Sólo texto"?',
        Confirm: "Confirmar",
        Cancel: "Cancelar",
        EmptyDirectoryNavigation: "La navegación del catálogo está vacía",
        CollapseAll: "Ampliar todo",
        ExpandAll: "Guarda todo",
        EmptyWebPageNavigation: "La navegación de la página está vacía",
        UseLine: '¿Desea confirmar el uso de las "líneas auxiliares"?',
        CancelLine: '¿Desea confirmar la cancelación de las "líneas auxiliares"?',
        UseAuxiliaryLine: "Utilizar líneas auxiliares",
        CancelAuxiliaryLine: "Cancelar las líneas auxiliares",
        ModifyParagraph: "Modificación de párrafos",
        Modify: "Modificar",
        TemporarySave: "Guardar temporalmente",
        CancelSave: "Cancelar Guardar",
        ModifyTip: 'Nota: Después de modificar este párrafo, haga clic en "Guardar temporalmente" y el contenido modificado podrá verse en la página "Documentos modificados".',
        DocumentTip: 'Esta función está sujeta al entorno del sistema, así que guarde el texto modificado en su artículo lo antes posible.',
        AlertSuccess: "Se trata de guardar temporalmente los cambios que ha realizado en su informe, el contenido editado será de color verde",
        SupportBrowser: '¡¡¡Su navegador actual no soporta la función de modificación de párrafos, por favor, utilice otro navegador!!!',
        FirstPage: "Inicio",
        LastPage: "Última página",
        PageNumber: "Número de la página", 
        Page: "Página", 
        NumberOfPages: "Número de páginas",
        Loading: "Cargando...",
        DifferentSimilarityTip: "Los diferentes colores de las frases indican diferentes grados de similitud",
        Red: "Rojo",
        Orange: "Naranja",
        Black: "Negro",
        Green: "Verde",
        SevereSimilarity: "Más del 70% de similitud (similitud alta, por favor, revise completamente)",
        SlightlySimilar: "40%-70% de similitud (similitud leve, por favor, revise lo que corresponda)",
        Qualified: "Aprobado",
        ViewDetailSentence: 'Para ver los resultados detallados de las frases, haga clic en las partes del documento marcadas en rojo y naranja',
        SentenceSimilarityTip: "Similitud de la frase",
        YourSentence: "Sus frases",
        Composite: "Global",
        Library: "Local",
        Internet: "Internet",
        SelfBuiltLibrary: "Repositorio propio",
        SimilarSentences: "Frases similares",
        SimilarOriginalFragment: "Fragmentos de las frases similares",
        Source: "Fuente",
        Journal: "Revistas académicas",
        Dissertation: "Tesis",
        AcademicConferences: "Conferencias académicas",
        BookData: "Datos de libros",
        University: "Repositorio de comparación conjunto de estudiantes universitarios",
        Title: "Título",
        Author: "Autor",
        Periodical: "Nombre de la revista",
        Issue: "Fecha de publicación",
        PeriodicalColumn: "Apartados de la revista",
        ClassificationNumber: "Número de clasificación",
        Funding: "Fondo de financiación",
        Abstract: "Resumen",
        PublicationDate: "Fecha de publicación",
        PeriodicalLevel: "Nivel de la revista",
        ISSN: "ISSN",
        DegreeAwarded: "Institución emisora del expediente",
        DegreeGrantingUnit: "Título otorgado",
        DegreeYear: "Año de graduación",
        Major: "Carrera especializada",
        TeacherName: "Nombre del supervisor",
        Conference: "Nombre de la conferencia",
        Organizer: "Organizador",
        ConferenceDate: "Fecha de la conferencia",
        ConferenceLocation: "Lugar de la conferencia",
        Chapter: "Capítulo",
        Publisher: "Editorial",
        ISBN: "ISBN",
        Provenance: "Procedencia",
        OpenSearch: "OpenSearch",
        Length: "Longitud",
        UploadTime: "Tiempo de subida",
        Keyword: "Palabras clave",
        BackTop: "Volver al principio",
        BasicInformation: "Información básica",
        PaperTitle: "Título del artículo",
        PaperTime: "Fecha del artículo",
        LocalLibrarySimilarity: "Similitud con el repositorio local",
        JournalLibrarySimilarity: "Similitud con el repositorio de revistas",
        DegreeLibrarySimilarity: "Similitud con el repositorio de tesis",
        MeetingSimilarity: "Similitud con el repositorio de artículos de conferencias",
        LibrarySimilarity: "Similitud con el repositorio de libros",
        InternetSimilarity: "Similitud con los datos de Internet",
        SelfbuiltSimilarity: "Similitud con el repositorio propio",
        SimilarityCalculationFormula: "Fórmula de cálculo de la similitud",
        Formula: "(similitud de la frase 1 + similitud de la frase 2 + ... + similitud de la frase n) / n",
        SimilarityRange: "Rango de similitud de las frases de 0,0 a 1,0",
        SimilarityRangeDetail: "La similitud de la frase verde se calcula como 0",
        SimilarityDistribution: "Distribución de la similitud de las frases",
        PointDistributionDiagram: "Distribución de puntos de las frases no aprobadas",
        Sentence: "Frases",
        LocalLibrariesTitle: "Recursos similares en el repositorio local",
        LocalTip: "No se han encontrado recursos similares en el repositorio local",
        Details: "Detalles",
        PutAway: "Guardar",
        ViewMore: "Ver más",
        InternetSimilarResources: "Recursos similares en Internet",
        InternetTip: "No se han encontrado recursos similares en Internet",
        PaperFooter: "Los informes de pruebas son generados por el sistema de pruebas de similitud de PaperPass.Net",
        Copyright: "Derecho intelectual",
        LoadingOriginal: "Cargando el artículo original, por favor espere...",
        Aditional: "Frases adicionales",
        Word: "Informe detallado.Versión Word",
        Text: "Informe detallado.Versión en texto plano",
    },
    "Français": {
        FlagshipVersion: "Edition ultime",
        SubmitTime: "Heure de soumission",
        PaperNumber: "Nombre de mots de l'article",
        OverallSimilarity: "Similitude globale",
        DetailReport: "Rapport",
        TextProofreading: "Relecture",
        ComprehensiveAssessment: "Evaluation",
        ViewOriginal: "Texte original",
        UseHelp: "Aide",
        Download: "Télécharger",
        DownloadOriginal: "Télécharger l'original",
        DownloadHTM: "Télécharger le rapport hors ligne",
        DownloadPDF: "Télécharger la version PDF",
        DownloadWord: "Télécharger la version WORD",
        SupportJavaScript: "Votre navigateur actuel Javascript est désactivé ! ! !",
        LoadingReport: "Il est en train de charger le rapport, veuillez patienter...",
        Similarity: "Similitude",
        SimilarityTip: "Pour afficher le rapport détaillé de la phrase, veuillez agrandir le côté droit !",
        AditionalSentences: "Page supplémentaire pour des phrases similaires",
        BlankPage: "[Cette page est vierge, veuillez consulter la page suivante]",
        SwitchMode: "Changer de mode",
        DirectoryNavigation: "Navigation du répertoire",
        WebpageNavigation: "Navigation de la page",
        ModifyDocument: "Modifier le document",
        AuxiliaryLine: "Ligne auxiliaire",
        PreviousPage: "Page précédente",
        NextPage: "Page suivante",
        Enter: "Entrer le numéro de page",
        Jump: "Entrer",
        Scale: "Agrandir et amoindrir",
        Zoom: "Agrandir",
        ZoomOut: "Amoindrir",
        ScalingRatio: "Rapport de mise à l'échelle",
        FitWidth: "Largeur appropriée",
        SuitableHeight: "Hauteur appropriée",
        OriginalSize: "Taille originale",
        WordMode: 'Êtes-vous sûr de passer en « Mode Word » ?',
        TextMode: 'Êtes-vous sûr de passer en « Mode texte brut » ?',
        Confirm: "Confirmer",
        Cancel: "Annuler",
        EmptyDirectoryNavigation: "La navigation du répertoire est vide",
        CollapseAll: "Etaler tout",
        ExpandAll: "Replier tout",
        EmptyWebPageNavigation: "La navigation de la page est vide",
        UseLine: 'Confirmer « Utiliser la ligne auxiliaire » ?',
        CancelLine: 'Confirmer « Annuler la ligne auxiliaire » ?',
        UseAuxiliaryLine: "Utiliser la ligne auxiliaire",
        CancelAuxiliaryLine: "Annuler la ligne auxiliaire",
        ModifyParagraph: "Révision de paragraphe",
        Modify: "Modifier",
        TemporarySave: "Sauvegarder temporairement",
        CancelSave: "Annuler sauvegarder",
        ModifyTip: 'Remarque : Après avoir modifié ce paragraphe, cliquez sur « Sauvegarder temporairement », le contenu modifié peut être visualisé dans la page « Modifier le document ».',
        DocumentTip: "Cette fonction est affectée par l'environnement système, veuillez enregistrer l'article révisé sur votre papier dès que possible.",
        AlertSuccess: "Il s'agit du contenu temporairement enregistré après avoir modifié le rapport, le contenu modifié deviendra vert",
        SupportBrowser: "Votre navigateur actuel ne prend pas en charge l'édition de paragraphes, veuillez utiliser un autre navigateur ! ! !",
        FirstPage: "Page de garde",
        LastPage: "Dernière page",
        PageNumber: "Page", 
        Page: "Page", 
        NumberOfPages: "Nombre de pages", 
        Loading: "Chargement...",
        DifferentSimilarityTip: "Différentes couleurs de phrases indiquent différentes similitudes",
        Red: "Rouge",
        Orange: "Orange",
        Black: "Noir",
        Green: "Vert",
        SevereSimilarity: "La similitude est supérieure à 70 % (gravement similaire, veuillez la réviser complètement)",
        SlightlySimilar: "La similitude est 40%-70% (légèrement similaire, veuillez la réviser le cas échéant)",
        Qualified: "Qualifié",
        ViewDetailSentence: 'Si vous souhaitez afficher les résultats de test détaillés des phrases, veuillez cliquer sur les parties marquées « rouge » et « orange » dans le papier',
        SentenceSimilarityTip: "Similitude de cette phrase",
        YourSentence: "Votre phrase",
        Composite: "Complet",
        Library: "Locale",
        Internet: "Internet",
        SelfBuiltLibrary: "Bibliothèque propre",
        SimilarSentences: "Phrase similaire",
        SimilarOriginalFragment: "Fragment original similaire",
        Source: "Origine",
        Journal: "Revues universitaires",
        Dissertation: "Thèses",
        AcademicConferences: "Conférences",
        BookData: "Données de livres",
        University: "Bibliothèque de comparaison commune des étudiants universitaires",
        Title: "Titre d'article",
        Author: "Auteur",
        Periodical: "Titre de la revue",
        Issue: "Date de publication",
        PeriodicalColumn: "Colonne de la revue",
        ClassificationNumber: "Numéro de classement",
        Funding: "Projet de fonds",
        Abstract: "Sommaire",
        PublicationDate: "Date de publication",
        PeriodicalLevel: "Niveau la périodique",
        ISSN: "ISSN",
        DegreeAwarded: "Unité d'attribution",
        DegreeGrantingUnit: "Diplôme attribué",
        DegreeYear: "Année de licence",
        Major: "Majeur",
        TeacherName: "Nom du tuteur",
        Conference: "Titre du conférence",
        Organizer: "Organisateur",
        ConferenceDate: "Date de la conférence",
        ConferenceLocation: "Lieu de la conférence",
        Chapter: "Chapitre",
        Publisher: "Maison d'édition",
        ISBN: "ISBN",
        Provenance: "Origine",
        OpenSearch: "OpenSearch",
        Length: "Longeur",
        UploadTime: "Heure du téléchargement",
        Keyword: "Mots-clés",
        BackTop: "Retour au sommet",
        BasicInformation: "Informations de base",
        PaperTitle: "Sujet de l'article",
        PaperTime: "Date de l'article",
        LocalLibrarySimilarity: "Similitude de la bibliothèque locale",
        JournalLibrarySimilarity: "Similitude de la bibliothèque de revues universitaires",
        DegreeLibrarySimilarity: "Similitude de la bibliothèque de thèses",
        MeetingSimilarity: "Similitude de la bibliothèque de conférences",
        LibrarySimilarity: "Similitude de la bibliothèque de livres",
        InternetSimilarity: "Similitude d'Internet",
        SelfbuiltSimilarity: "Similitude de la bibliothèque propre",
        SimilarityCalculationFormula: "Formule de calcul de similitude",
        Formula: "( la similitude de phrase 1 + la similitude de phrase 2 + ... + la similitude de phrase n ) /n",
        SimilarityRange: "Plage de similitude des phrases 0,0～1,0",
        SimilarityRangeDetail: "La similitude de la phrase verte est calculée comme 0",
        SimilarityDistribution: "Répartition des similarités de phrases",
        PointDistributionDiagram: "Punctogramme des phrases non qualifiées",
        Sentence: "Phrase",
        LocalLibrariesTitle: "Ressources similaires dans la bibliothèque locale",
        LocalTip: "Aucune ressource présentant une grande similitude avec la bibliothèque locale n'a été trouvée",
        Details: "Informations détaillées",
        PutAway: "Replier ",
        ViewMore: "voir plus",
        InternetSimilarResources: "Ressources similaires sur Internet",
        InternetTip: "Aucune ressource présentant une grande similitude avec Internet n'a été trouvée",
        PaperFooter: "Le rapport de test est généré par le système de test de similarité des documents PaperPass.Net",
        Copyright: "Plagiat",
        LoadingOriginal: "Il est en train de charger le texte original, veuillez patienter...",
        Aditional: "Phrase supplémentaire",
        Word: "Rapport détaillé.Version Word",
        Text: "Rapport détaillé.Version texte brut",
    },
    "Italiano": {
        FlagshipVersion: "Edizione ammiraglia",
        SubmitTime: "Data di presentazione",
        PaperNumber: "Numero di parole nell'articolo",
        OverallSimilarity: "Somiglianza complessiva",
        DetailReport: "Rapporto",
        TextProofreading: "Correzione di bozze",
        ComprehensiveAssessment: "Valutazione",
        ViewOriginal: "Articolo originale",
        UseHelp: "Aiuto",
        Download: "Scarica",
        DownloadOriginal: "Scarica l'originale",
        DownloadHTM: "Scarica il rapporto offline",
        DownloadPDF: "Scarica la versione PDF",
        DownloadWord: "Scarica la versione WORD",
        SupportJavaScript: "Javascript è disabilitato nel tuo attuale browser!",
        LoadingReport: "Caricamento del rapporto, attendere prego...",
        Similarity: "Somiglianza",
        SimilarityTip: "Per visualizzare il rapporto dettagliato della frase, espandi a destra!",
        AditionalSentences: "Frasi simili completano la pagina",
        BlankPage: "[Questa pagina è vuota, controlla la pagina successiva]",
        SwitchMode: "Modalità di commutazione",
        DirectoryNavigation: "Navigazione di indice",
        WebpageNavigation: "Navigazione di pagine",
        ModifyDocument: "Modificare il documento",
        AuxiliaryLine: "Linee ausiliarie",
        PreviousPage: "Pagina precedente",
        NextPage: "Pagina successiva",
        Enter: "Inserisci il numero di pagina",
        Jump: "Salta",
        Scale: "Rimpicciolisci",
        Zoom: "Ingrandisci",
        ZoomOut: "Riduci",
        ScalingRatio: "Rimpicciolisci la scala",
        FitWidth: "Larghezza adatta",
        SuitableHeight: "Altezza adatta",
        OriginalSize: "Dimensione originale",
        WordMode: 'Vuoi passare alla modalità "Word"?',
        TextMode: 'Vuoi passare alla modalità "Solo testo"?',
        Confirm: "Sì",
        Cancel: "Cancella",
        EmptyDirectoryNavigation: "La navigazione verso l'indice è vuota",
        CollapseAll: "Espandi tutto",
        ExpandAll: "Chiudi tutto",
        EmptyWebPageNavigation: "La pagina di navigazione è vuota",
        UseLine: 'Volete confermare "Usare le linee ausiliarie"?',
        CancelLine: 'Confermare "Cancellare le linee ausiliarie"?',
        UseAuxiliaryLine: "Utilizzare le linee ausiliarie",
        CancelAuxiliaryLine: "Cancellare le linee ausiliarie",
        ModifyParagraph: "Modifica del paragrafo",
        Modify: "Modifica",
        TemporarySave: "Salva temporaneamente",
        CancelSave: "Cancella il salvataggio",
        ModifyTip: "Nota: dopo aver modificato questo paragrafo, clicca su 'Salva temporaneamente' e il contenuto modificato può essere visualizzato nella pagina 'Documento modificato'.",
        DocumentTip: "Questa funzione è soggetta all'ambiente del sistema, quindi per favore salva l'articolo rivisto sul tuo giornale il prima possibile.",
        AlertSuccess: "Questo è un salvataggio temporaneo delle modifiche che hai fatto al tuo rapporto, il contenuto modificato sarà verde",
        SupportBrowser: 'Il tuo browser attuale non supporta la funzione di modifica dei paragrafi, per favore usa un altro browser!',
        FirstPage: "Prima pagina",
        LastPage: "Ultima pagina",
        PageNumber: "Pagina", 
        Page: "Pagina", 
        NumberOfPages: "Pagine",
        Loading: "Caricamento in corso...",
        DifferentSimilarityTip: "I diversi colori delle frasi indicano diversi gradi di somiglianza",
        Red: "rosso",
        Orange: "arancione",
        Black: "nero",
        Green: "verde",
        SevereSimilarity: "Oltre il 70% di somiglianza (somiglianza pesante, si prega di rivedere completamente)",
        SlightlySimilar: "40%-70% di somiglianza (leggera somiglianza, si prega di rivedere come appropriato)",
        Qualified: "Passa",
        ViewDetailSentence: 'Per vedere i risultati dettagliati della frase clicca sulle parti del giornale segnate in rosso e arancione',
        SentenceSimilarityTip: "Somiglianza della frase",
        YourSentence: "Le Sue frasi",
        Composite: "Sintesi",
        Library: "Locale",
        Internet: "Internet",
        SelfBuiltLibrary: "Database autocostruito",
        SimilarSentences: "Frasi simili",
        SimilarOriginalFragment: "Frammenti originali simili",
        Source: "Fonte",
        Journal: "Periodici accademici",
        Dissertation: "Dissertazione di lauree",
        AcademicConferences: "Conferenze accademiche",
        BookData: "Dati del libro",
        University: "Comparatore di studenti universitari comuni",
        Title: "Titolo",
        Author: "Autore",
        Periodical: "Nome del Periodico",
        Issue: "Data di pubblicazione",
        PeriodicalColumn: "Sezione del Periodico",
        ClassificationNumber: "Numero di classificazione",
        Funding: "Voce del fondo",
        Abstract: "Abstract",
        PublicationDate: "Data di pubblicazione",
        PeriodicalLevel: "Livello del Periodico",
        ISSN: "ISSN",
        DegreeAwarded: "Premiato da",
        DegreeGrantingUnit: "Laurea conseguita",
        DegreeYear: "Anno di laurea",
        Major: "Specializzazione di materia",
        TeacherName: "Nome del relatore",
        Conference: "Nome della conferenza",
        Organizer: "Organizzatore",
        ConferenceDate: "Data della conferenza",
        ConferenceLocation: "Sede della conferenza",
        Chapter: "Capitolo",
        Publisher: "Editore",
        ISBN: "ISBN",
        Provenance: "Provenienza",
        OpenSearch: "OpenSearch",
        Length: "Lunghezza",
        UploadTime: "Data di caricamento",
        Keyword: "Parole chiave",
        BackTop: "Torna all'inizio",
        BasicInformation: "Informazioni di base",
        PaperTitle: "Titolo della tesi",
        PaperTime: "Data della tesi",
        LocalLibrarySimilarity: "Similitudine del Database locale",
        JournalLibrarySimilarity: "Similitudine del Database dei Periodici",
        DegreeLibrarySimilarity: "Similitudine del Database delle Lauree",
        MeetingSimilarity: "Similitudine del Database delle Conferenze",
        LibrarySimilarity: "Similitudine del Database dei Libri",
        InternetSimilarity: "Similitudine con Internet",
        SelfbuiltSimilarity: "Similitudine del Database autocostruito",
        SimilarityCalculationFormula: "Formula per il calcolo del similitudine",
        Formula: "(Somiglianza della frase 1 + Somiglianza della frase 2 + ... + Somiglianza della frase n) / n",
        SimilarityRange: "Gamma di similarità delle frasi da 0,0 a 1,0 ",
        SimilarityRangeDetail: "La somiglianza delle frasi verdi è calcolata come 0",
        SimilarityDistribution: "Distribuzione della somiglianza delle frasi",
        PointDistributionDiagram: "Distribuzione dei punti delle frasi non qualificate",
        Sentence: "Frasi",
        LocalLibrariesTitle: "Risorse simili al Database locale",
        LocalTip: "Nessuna risorsa trovata che sia simile al Database locale",
        Details: "Dettagli",
        PutAway: "Chiudi",
        ViewMore: "Vedi di più",
        InternetSimilarResources: "Risorse simili a Internet",
        InternetTip: "Nessuna risorsa trovata che sia simile a Internet",
        PaperFooter: "I rapporti dei test sono generati dal sistema di test di somiglianza della letteratura PaperPass.Net",
        Copyright: "Diritto d'autore",
        LoadingOriginal: "Caricamento articolo originale, attendere prego...",
        Aditional: "Frasi aggiuntive",
        Word: "Rapporto dettagliato.Versione Word",
        Text: "Rapporto dettagliato.Versione in testo semplice",
    },
    "Português": {
        FlagshipVersion: "Edição flagship",
        SubmitTime: "Hora de envio",
        PaperNumber: "Contagem de palavra",
        OverallSimilarity: "Similaridade geral",
        DetailReport: "Relatório",
        TextProofreading: "Revisão",
        ComprehensiveAssessment: "Avaliação",
        ViewOriginal: "Original",
        UseHelp: "Ajuda",
        Download: "Download",
        DownloadOriginal: "Baixar original",
        DownloadHTM: "Baixar relatório offline",
        DownloadPDF: "Baixe a versão em PDF",
        DownloadWord: "Baixe a versão WORD",
        SupportJavaScript: "O Javascript do seu navegador actual está desabilitado!!!",
        LoadingReport: "O relatório está a carregar, por favor aguarde...",
        Similarity: "Similaridade",
        SimilarityTip: "Para o relatório detalhado de frase, por favor, expanda o lado direito!",
        AditionalSentences: "Página suplementar para frases semelhantes",
        BlankPage: "[Esta página está em branco, por favor veja a próxima página]",
        SwitchMode: "Mudar de modo",
        DirectoryNavigation: "Navegação no directório",
        WebpageNavigation: "Navegação na página",
        ModifyDocument: "Documento modificado",
        AuxiliaryLine: "Linha-guia",
        PreviousPage: "Página anterior",
        NextPage: "Página seguinte",
        Enter: "Digite o número da página",
        Jump: "Ir para",
        Scale: "Ampliar ou reduzir",
        Zoom: "Ampliar",
        ZoomOut: "Reduzir",
        ScalingRatio: "Escala",
        FitWidth: "Ajustar à largura",
        SuitableHeight: "Ajustar à altura",
        OriginalSize: "Tamanho original",
        WordMode: 'Mudar para o "Modo de Word"?',
        TextMode: 'Mudar para o "Modo de Texto simples"?',
        Confirm: "Confirmar",
        Cancel: "Cancelar",
        EmptyDirectoryNavigation: "A navegação do diretório está vazia",
        CollapseAll: "Expandir tudo",
        ExpandAll: "Fechar tudo",
        EmptyWebPageNavigation: "A navegação da página está vazia",
        UseLine: 'Confirma para "Usar linha-guia"?',
        CancelLine: 'Confirma para "Cancelar linha-guia"?',
        UseAuxiliaryLine: "Usar linha-guia",
        CancelAuxiliaryLine: "Cancelar linha-guia",
        ModifyParagraph: "Modificação de parágrafo",
        Modify: "Modificar",
        TemporarySave: "Guardar temporariamente",
        CancelSave: "Cancelar para guardar",
        ModifyTip: 'Observação: Depois de modificar este parágrafo, clique em "Guardar temporariamente". O conteúdo modificado pode ser visto na página "Documento modificado".',
        DocumentTip: 'Esta função é sujeita ao ambiente do sistema. Por favor, guarde o documento modificado na sua tese o mais rápido possível.',
        AlertSuccess: "Este é o conteúdo guardado temporariamente depois da sua modificação no relatório. O conteúdo editado ficará em cor verde",
        SupportBrowser: 'O seu navegador actual não suporta a modificação de parágrafo, por favor, use outro navegador!!!',
        FirstPage: "Primeira página",
        LastPage: "Última página",
        PageNumber: "Página No.", 
        Page: "Página", 
        NumberOfPages: "Número de páginas",
        Loading: "Carregando...",
        DifferentSimilarityTip: "As cores diferentes de frases indicam similaridades diferentes",
        Red: "Vermelho",
        Orange: "Cor de laranja",
        Black: "Preto",
        Green: "Verde",
        SevereSimilarity: "Mais de 70% de similaridade (similaridade grave, por favor, modifique completamente)",
        SlightlySimilar: "40% -70% de similaridade (similaridade ligeira, por favor, modifique conforme apropriado)",
        Qualified: "Qualificado",
        ViewDetailSentence: 'Para obter os resultados de deteccção detalhados das frases, clique nas partes marcadas em "vermelho" e "cor de laranja" na tese',
        SentenceSimilarityTip: "Similaridade desta frase",
        YourSentence: "A sua frase",
        Composite: "Integrado",
        Library: "Local",
        Internet: "Internet",
        SelfBuiltLibrary: "Banco de dados auto-construído",
        SimilarSentences: "Frases semelhantes",
        SimilarOriginalFragment: "Fragmentos de original semelhantes",
        Source: "Fonte",
        Journal: "Periódicos académicos",
        Dissertation: "Dissertações académicas",
        AcademicConferences: "Conferências académicas",
        BookData: "Dados de livros",
        University: "Banco de dados de comparação conjunto de teses dos estudantes universitários",
        Title: "Título",
        Author: "Autor",
        Periodical: "Título de periódico",
        Issue: "Data de publicação",
        PeriodicalColumn: "Coluna de periódico",
        ClassificationNumber: "Classificação No.",
        Funding: "Programa de fundos",
        Abstract: "Resumo",
        PublicationDate: "Data de publicação",
        PeriodicalLevel: "Nível de periódico",
        ISSN: "ISSN",
        DegreeAwarded: "Autoridade de concessão",
        DegreeGrantingUnit: "Grau académico conferido",
        DegreeYear: "Ano de graduação",
        Major: "Ano de graduação",
        TeacherName: "Nome do tutor",
        Conference: "Nome de conferência",
        Organizer: "Organizador",
        ConferenceDate: "Data de conferência",
        ConferenceLocation: "Local de conferência",
        Chapter: "Capítulo",
        Publisher: "Editora",
        ISBN: "ISBN",
        Provenance: "Origem",
        OpenSearch: "AbrirPesquisa",
        Length: "Comprimento",
        UploadTime: "Data de carregamento",
        Keyword: "Palavras-chave",
        BackTop: "Voltar ao topo",
        BasicInformation: "Informação básica",
        PaperTitle: "Título de tese",
        PaperTime: "Tempo de tese",
        LocalLibrarySimilarity: "Similaridade com o banco de dados local",
        JournalLibrarySimilarity: "Similaridade com o banco de dados de periódicos",
        DegreeLibrarySimilarity: "Similaridade com o banco de dados de dissertações académicas",
        MeetingSimilarity: "Similaridade com o banco de dados de conferências",
        LibrarySimilarity: "Similaridade com o banco de dados de livros",
        InternetSimilarity: "Similaridade com os recursos da Internet",
        SelfbuiltSimilarity: "Similaridade com o banco de dados auto-construído",
        SimilarityCalculationFormula: "Fórmula de cálculo de similaridade",
        Formula: "(Similaridade da frase 1 + similaridade da frase 2 + ... + similaridade da frase n)/n",
        SimilarityRange: "A similaridade de frase varia de 0,0 a 1,0 ",
        SimilarityRangeDetail: "A similaridade de frase verde é calculada como 0",
        SimilarityDistribution: "Distribuição de similaridade de frases",
        PointDistributionDiagram: "Distribuição de pontos de frases não qualificadas",
        Sentence: "Frases",
        LocalLibrariesTitle: "Recursos semelhantes ao banco de dados local",
        LocalTip: "Nenhum recurso encontrado de similaridade alta com o banco de dados local",
        Details: "Detalhes",
        PutAway: "Fechar",
        ViewMore: "Ver mais",
        InternetSimilarResources: "Recursos semelhantes à Internet",
        InternetTip: "Nenhum recurso encontrado de similaridade alta com a Internet",
        PaperFooter: "O relatório de detecção é gerado pelo sistema de detecção de similaridade de literatura PaperPass.Net",
        Copyright: "Direito autoral",
        LoadingOriginal: "O texto original está a carregar, por favor aguarde...",
        Aditional: "Frases suplementares",
        Word: "Relatório detalhado.Versão em Word",
        Text: "Relatório detalhado.Versão em texto simples",
    },
    "Türkçe": {
        FlagshipVersion: "Nihai Sürüm",
        SubmitTime: "Gönderim zamanı",
        PaperNumber: "Kelime sayısı",
        OverallSimilarity: "Genel benzerlik",
        DetailReport: "Rapor",
        TextProofreading: "Düzeltme yapma",
        ComprehensiveAssessment: "Değerlendirme",
        ViewOriginal: "Orijinal metin",
        UseHelp: "Yardım",
        Download: "indirmek",
        DownloadOriginal: "Orijinali İndir",
        DownloadHTM: "Çevrimdışı Raporu İndir",
        DownloadPDF: "PDF sürümünü indirin",
        DownloadWord: "WORD sürümünü indirin",
        SupportJavaScript: "Mevcut tarayıcınız Javascript devre dışı! ! !",
        LoadingReport: "Rapor yükleniyor, lütfen bekleyin...",
        Similarity: "Benzerlik",
        SimilarityTip: "Cümlenin ayrıntılı raporunu görmek için lütfen sağ tarafı genişletin!",
        AditionalSentences: "Benzer cümleler için ek sayfa",
        BlankPage: "[Bu sayfa boş, lütfen sonraki sayfayı inceleyin]",
        SwitchMode: "Modu değiştirme",
        DirectoryNavigation: "İçindekiler rehberliği",
        WebpageNavigation: "Sayfa rehberliği",
        ModifyDocument: "Belgeyi değiştirme",
        AuxiliaryLine: "Yardımcı hat",
        PreviousPage: "Önceki sayfa",
        NextPage: "Sonraki Sayfa",
        Enter: "Sayfa numarasını girin",
        Jump: "Zıplama",
        Scale: "Yakınlaştırma",
        Zoom: "Büyütme",
        ZoomOut: "Uzaklaştırma",
        ScalingRatio: "Ölçekleme oranı",
        FitWidth: "Uygun genişlik",
        SuitableHeight: "Uygun yükseklik",
        OriginalSize: "Orijinal boyut",
        WordMode: '"Word Modu"na geçmek istediğinizden emin misiniz?',
        TextMode: '"Sadece Metin Görülen Modu"na geçmek istediğinizden emin misiniz?',
        Confirm: "Emin",
        Cancel: "İptal",
        EmptyDirectoryNavigation: "İçindekiler rehberliği boştur",
        CollapseAll: "Hepsini genişlet",
        ExpandAll: "Hepsini daralt",
        EmptyWebPageNavigation: "Sayfa rehberliği boştur",
        UseLine: 'Yardımcı hattı kullandığınızdan emin misin?',
        CancelLine: 'Yardımcı hattı iptal ettiğinden emin misin?',
        UseAuxiliaryLine: "Yardımcı hattı kullanma",
        CancelAuxiliaryLine: "Yardımcı hattı iptal etme",
        ModifyParagraph: "Paragraf düzeltme",
        Modify: "Tekrar düzeltme yapma",
        TemporarySave: "Geçici kaydetme",
        CancelSave: "Kaydetmeyi iptal etme",
        ModifyTip: 'Not: Bu paragrafı değiştirdikten sonra "Geçici  Kaydetme"ye tıklayın, değiştirilen içerik "Belgeyi Dülzetme" sayfasında görüntülenebilir.',
        DocumentTip: 'Bu işlev sistem ortamından etkilenir, lütfen gözden geçirilmiş makaleyi mümkün olan en kısa sürede makalenize kaydedin.',
        AlertSuccess: "Bu, raporu düzelttikten sonra geçici olarak kaydedilen içeriktir, düzenlenen içerik yeşile döner",
        SupportBrowser: 'Mevcut tarayıcınız paragraf düzenlemeyi desteklemiyor, lütfen başka bir tarayıcı kullanın! ! !',
        FirstPage: "İlk sayfa",
        LastPage: "Son sayfa",
        PageNumber: "Sayfa numarası", 
        Page: "Sayfa", 
        NumberOfPages: "Sayfa sayısı",
        Loading: "Yükleniyor...",
        DifferentSimilarityTip: "Cümlelerin farklı renkleri farklı benzerlikleri gösterir",
        Red: "Kırmızı",
        Orange: "Turuncu",
        Black: "Siyah",
        Green: "Yeşil",
        SevereSimilarity: "Benzerlik %70'den fazla (Çok benzer, lütfen tamamen gözden geçirin)",
        SlightlySimilar: "Benzerlik %40-70 (Biraz benzer, lütfen uygun şekilde değiştirin)",
        Qualified: "Nitelikli",
        ViewDetailSentence: 'Cümlelerin detaylı test sonuçlarını görmek isterseniz lütfen makaledeki "kırmızı" ve "turuncu" işaretli yerlere tıklayınız.',
        SentenceSimilarityTip: "Bu cümlenin benzerliği",
        YourSentence: "Cümleniz",
        Composite: "Kapsamlı",
        Library: "Yerel",
        Internet: "İnternet",
        SelfBuiltLibrary: "Kendi kendine oluşturulmuş kitaplık",
        SimilarSentences: "Benzer cümle",
        SimilarOriginalFragment: "Orijinaline benzer paragraf",
        Source: "Kaynak",
        Journal: "Akademik dergiler",
        Dissertation: "Diploma tezi",
        AcademicConferences: "Akademik konferans",
        BookData: "Kitap verileri",
        University: "Üniversite Öğrencilerinin Ortak Karşılaştırma Kitaplığı",
        Title: "Başlık",
        Author: "Yazar",
        Periodical: "Dergi başlığı",
        Issue: "Yayın tarihi",
        PeriodicalColumn: "Dergi sütunu",
        ClassificationNumber: "Sınıflandırma numarası",
        Funding: "Vakıf projesi",
        Abstract: "Özet",
        PublicationDate: "Yayın zamanı",
        PeriodicalLevel: "Dergi düzeyi",
        ISSN: "ISSN",
        DegreeAwarded: "Verildiği örgüt",
        DegreeGrantingUnit: "Verildiği diploma",
        DegreeYear: "Diploma yıllık",
        Major: "Anabilim dalı",
        TeacherName: "Danışman adı",
        Conference: "Konferans adı",
        Organizer: "Düzenleyen örgüt",
        ConferenceDate: "Konferans zamanı",
        ConferenceLocation: "Konferans yeri",
        Chapter: "Bölüm",
        Publisher: "Yayınevi",
        ISBN: "ISBN",
        Provenance: "Kaynak ",
        OpenSearch: "Açık arama",
        Length: "Uzunluk",
        UploadTime: "Yükleme tarihi",
        Keyword: "Anahtar kelimeler",
        BackTop: "Başa dön",
        BasicInformation: "Temel bilgiler",
        PaperTitle: "Makale konusu",
        PaperTime: "Makale zamanı",
        LocalLibrarySimilarity: "Yerel kitaplık benzerliği",
        JournalLibrarySimilarity: "Dergi kitaplığı benzerliği",
        DegreeLibrarySimilarity: "Dergi kitaplığı benzerliği",
        MeetingSimilarity: "Konferans kitaplığı benzerliği",
        LibrarySimilarity: "Ktütüphane benzerliği",
        InternetSimilarity: "İnternet benzerliği",
        SelfbuiltSimilarity: "Kendi kendine oluşturulmuş kitaplık benzerliği",
        SimilarityCalculationFormula: "Benzerlik hesaplama formülü",
        Formula: "(Cümle 1 benzerlik + cümle 2 benzerlik +…+cümle n benzerlik) / n",
        SimilarityRange: "Cümle benzerlik aralığı 0.0～1.0",
        SimilarityRangeDetail: "Yeşil cümle benzerliği 0 olarak hesaplanır",
        SimilarityDistribution: "Cümle benzerlik dağılımı",
        PointDistributionDiagram: "Niteliksiz cümlelerin nokta dağılım şeması",
        Sentence: "Cümle",
        LocalLibrariesTitle: "Yerel kitaplıkta benzer kaynaklar",
        LocalTip: "Yerel kitaplıkla yüksek benzerlik gösteren hiçbir kaynak bulunamadı",
        Details: "Detaylar",
        PutAway: "Bırakma",
        ViewMore: "Daha fazla görme",
        InternetSimilarResources: "İnternete benzer kaynaklar",
        InternetTip: "İnternete çok benzeyen bir kaynak bulunamadı",
        PaperFooter: "Test raporu, PaperPass.Net belge benzerlik denetim sistemi tarafından oluşturulur.",
        Copyright: "Telif hakkı",
        LoadingOriginal: "Orijinal metin yükleniyor, lütfen bekleyin...",
        Aditional: "Ek cümle",
        Word: "Ayrıntılı rapor.Word versiyonu",
        Text: "Detaylı rapor.Sadece metin görülen versiyonu",
    },
    "Melayu": {
        FlagshipVersion: "Edisi Utama",
        SubmitTime: "Masa penghantaran",
        PaperNumber: "Kiraan perkataan tesis",
        OverallSimilarity: "Kesamaan keseluruhan",
        DetailReport: "Laporan",
        TextProofreading: "Proofreading dan semakan",
        ComprehensiveAssessment: "Menilai",
        ViewOriginal: "Teks asal",
        UseHelp: "Bantuan",
        Download: "Muat turun",
        DownloadOriginal: "Muat turun Asal",
        DownloadHTM: "Muat Turun Laporan Luar Talian",
        DownloadPDF: "Muat turun versi PDF",
        DownloadWord: "Muat turun versi WORD",
        SupportJavaScript: "Javascript dilumpuhkan dalam penyemak imbas semasa anda!!!",
        LoadingReport: "Memuatkan laporan, sila menunggu...",
        Similarity: "Kesamaan",
        SimilarityTip: "Untuk melihat laporan terperinci kalimat, luaskan sebelah kanan!",
        AditionalSentences: "Halaman tambahan untuk ayat yang keserupaan",
        BlankPage: "[Halaman ini kosong, sila lihat halaman seterusnya]",
        SwitchMode: "Tukar mod",
        DirectoryNavigation: "Navigasi direktori",
        WebpageNavigation: "Navigator halaman",
        ModifyDocument: "Modifikasi dokumen",
        AuxiliaryLine: "Garisan tambahan",
        PreviousPage: "Halaman sebelum",
        NextPage: "Halaman seterus",
        Enter: "Masukkan nombor halaman",
        Jump: "Lompat",
        Scale: "Zum",
        Zoom: "Membesarkan",
        ZoomOut: "Mengecilkan",
        ScalingRatio: "Nisbah penskalaan",
        FitWidth: "Lebar sesuai",
        SuitableHeight: "Tinggi sesuai",
        OriginalSize: "Saiz asal",
        WordMode: 'Adakah anda pasti beralih ke "Word Mod"?',
        TextMode: 'Adakah anda pasti beralih ke "mod teks"?',
        Confirm: "Pasti",
        Cancel: "Batal",
        EmptyDirectoryNavigation: "Navigasi direktori kosong",
        CollapseAll: "Luaskan semua",
        ExpandAll: "Runtuhkan semua",
        EmptyWebPageNavigation: "Navigasi halaman kosong",
        UseLine: 'Sahkan "Gunakan garisan tambahan"?',
        CancelLine: 'Sahkan "batalkan garisan tambahan"?',
        UseAuxiliaryLine: "Gunakan garisan tambahan",
        CancelAuxiliaryLine: "Batalkan garisan tambahan",
        ModifyParagraph: "Pengubahsuaian perenggan",
        Modify: "Modifikasi",
        TemporarySave: "Menyimpan sementara",
        CancelSave: "Batalkan menyimpan",
        ModifyTip: 'Perhatian: Setelah mengubah perenggan , klik "Menyimpan sementara", isi yang diubah dapat dilihat di halaman "Modifikasi dokumen".',
        DocumentTip: 'Fungsi ini dipengaruhi oleh lingkungan sistem, harap simpan artikel yang disemak ke tesis anda secepat mungkin.',
        AlertSuccess: "Ini adalah kandungan yang disimpan sementara setelah anda mengubah laporan, kandungan yang diedit akan berubah menjadi hijau",
        SupportBrowser: 'Penyemak imbas anda tidak menyokong pengubahsuaian perenggan, sila gunakan penyemak imbas lain! ! !',
        FirstPage: "Laman utama",
        LastPage: "Halaman akhir",
        PageNumber: "Nombor halaman", 
        Page: "Halaman", 
        NumberOfPages: "Bilangan halaman",
        Loading: "Memuat ...", 
        DifferentSimilarityTip: "Warna ayat yang berbeza menunjukkan persamaan yang berbeza",
        Red: "Merah",
        Orange: "Jingga",
        Black: "Hitam",
        Green: "Hijau",
        SevereSimilarity: "Lebih daripada 70% kesamaan (kesamaan tinggi, sila ubah secara komprehensif)",
        SlightlySimilar: "40% -70% kesamaan (agak kesamaan, sila ubah mengikut kesesuaian)",
        Qualified: "Lulus",
        ViewDetailSentence: 'Sekiranya anda ingin melihat keputusan ujian terperinci ayat, sila klik bahagian bertanda "merah" dan "jingga" di dalam tesis',
        SentenceSimilarityTip: "Kesamaan ayat",
        YourSentence: "Ayat anda",
        Composite: "Komprehensif",
        Library: "Tempatan",
        Internet: "Internet",
        SelfBuiltLibrary: "Pangkalan data tesis pengguna sendiri",
        SimilarSentences: "Ayat serupa",
        SimilarOriginalFragment: "Kesama serpihan asal",
        Source: "Sumber",
        Journal: "Jurnal akademik",
        Dissertation: "Tesis",
        AcademicConferences: "Seminar akademik",
        BookData: "Data pustaka",
        University: "Perpustakaan Perbandingan Kesatuan Pelajar Universiti",
        Title: "Tajuk",
        Author: "Pengarang",
        Periodical: "Nama jurnal",
        Issue: "Tarikh penerbitan",
        PeriodicalColumn: "Bahagian jurnal",
        ClassificationNumber: "Nombor klasifikasi",
        Funding: "Projek dana",
        Abstract: "Ringkasan",
        PublicationDate: "Tarikh diterbitkan",
        PeriodicalLevel: "Tahap jurnal",
        ISSN: "ISSN",
        DegreeAwarded: "Pemberian kuasa",
        DegreeGrantingUnit: "Pemberian ijazah",
        DegreeYear: "Tahun ijazah",
        Major: "Kursus",
        TeacherName: "Nama tutor",
        Conference: "Nama seminar",
        Organizer: "Penganjur",
        ConferenceDate: "Masa seminar",
        ConferenceLocation: "Lokasi seminar",
        Chapter: "Penggal",
        Publisher: "Rumah penerbitan",
        ISBN: "ISBN",
        Provenance: "Asal",
        OpenSearch: "Carian terbuka",
        Length: "Panjang",
        UploadTime: "Masa muat naik",
        Keyword: "Kata kunci",
        BackTop: "kembali ke puncak",
        BasicInformation: "Maklumat asas",
        PaperTitle: "Topik tesis",
        PaperTime: "Masa tesis dalam laporan talian",
        LocalLibrarySimilarity: "Kesamaan pangkalan data tempatan",
        JournalLibrarySimilarity: "Kesamaan pangkalan data jurnal",
        DegreeLibrarySimilarity: "Kesamaan pangkalan data tesis",
        MeetingSimilarity: "Kesamaan pangkalan data tesis seminar akademik ",
        LibrarySimilarity: "Kesamaan pangkalan data pustaka",
        InternetSimilarity: "Kesamaan pangkalan data internet",
        SelfbuiltSimilarity: "Kesamaan pangkalan data tesis pengguna sendiri",
        SimilarityCalculationFormula: "Formula pengiraan kesamaan",
        Formula: "(Ayat 1 kesamaan + ayat 2 kesamaan +… + ayat n kesamaan) / n",
        SimilarityRange: "Julat kesamaan ayat 0.0 ～ 1.0",
        SimilarityRangeDetail: "Kesamaan ayat hijau dikira sebagai 0",
        SimilarityDistribution: "Pembahagian kesamaan ayat",
        PointDistributionDiagram: "Gambarajah pembahagian titik bagi ayat yang tidak layak",
        Sentence: "Ayat",
        LocalLibrariesTitle: "Sumber serupa pangkalan data tempatan",
        LocalTip: "Tidak ada sumber dengan persamaan tinggi dengan pangkalan data tempatan",
        Details: "Perincian",
        PutAway: "Ketepikan",
        ViewMore: "Lihat lagi",
        InternetSimilarResources: "Sumber serupa pangkalan data internet",
        InternetTip: "Tidak menemui sumber yang tinggi kesamaan pangkalan data internet",
        PaperFooter: "Laporan pemeriksaan dihasilkan oleh sistem pemeriksaan kesamaan dokumen PaperPass.Net",
        Copyright: "Hak cipta",
        LoadingOriginal: "Memuatkan teks asal, sila menunggu...",
        Aditional: "Ayat tambahan",
        Word: "Laporan terperinci.Versi Word",
        Text: "Laporan terperinci.Versi teks",
    },
    "Indonesia": {
        FlagshipVersion: "Edisi Unggulan",
        SubmitTime: "Waktu pengiriman",
        PaperNumber: "Jumlah kata",
        OverallSimilarity: "Kesamaan keseluruhan",
        DetailReport: "Laporan",
        TextProofreading: "Pengoreksian",
        ComprehensiveAssessment: "Evaluasi",
        ViewOriginal: "Teks asli",
        UseHelp: "Bantuan",
        Download: "Unduh",
        DownloadOriginal: "Unduh Asli",
        DownloadHTM: "Unduh Laporan Offline",
        DownloadPDF: "Unduh versi PDF",
        DownloadWord: "Unduh versi WORD",
        SupportJavaScript: "JavaScript browser Anda saat ini dinonaktifkan!!!",
        LoadingReport: "Memuat laporan, harap tunggu",
        Similarity: "Kesamaan",
        SimilarityTip: "Untuk melihat laporan rinci pada kalimat, harap perluas sisi kanan!",
        AditionalSentences: "Halaman tambahan dari kalimat serupa",
        BlankPage: "[Halaman ini kosong, silakan periksa halaman berikutnya]",
        SwitchMode: "Beralih mode",
        DirectoryNavigation: "Navigasi Daftar Isi",
        WebpageNavigation: "Navigasi halaman",
        ModifyDocument: "Modifikasi dokumen",
        AuxiliaryLine: "Garis bantu",
        PreviousPage: "Halaman sebelumnya",
        NextPage: "Halaman selanjutnya",
        Enter: "Masukkan nomor halaman",
        Jump: "Melompat",
        Scale: "Mengubah skala",
        Zoom: "Perbesar",
        ZoomOut: "Persempit",
        ScalingRatio: "Skala",
        FitWidth: "Lebar yang sesuai",
        SuitableHeight: "Tinggi yang sesuai",
        OriginalSize: "Skala asli",
        WordMode: 'Apakah Anda pasti untuk beralih ke "mode Word"?',
        TextMode: 'Apakah Anda pasti untuk beralih ke "mode hanya teks"?',
        Confirm: "Ya",
        Cancel: "Batal",
        EmptyDirectoryNavigation: "Navigasi daftar isi kosong",
        CollapseAll: "Melebarkan semua",
        ExpandAll: "Singkirkan semua",
        EmptyWebPageNavigation: "Navigasi halaman kosong",
        UseLine: 'Konfirmasi "gunakan garis bantu"?',
        CancelLine: 'Konfirmasi "batalkan garis bantu"?',
        UseAuxiliaryLine: "Gunakan garis bantu",
        CancelAuxiliaryLine: "Batalkan garis bantu",
        ModifyParagraph: "Modifikasi paragraf",
        Modify: "Modifikasi",
        TemporarySave: "Simpan sementara",
        CancelSave: "Batalkan penyimpanan",
        ModifyTip: 'Catatan: setelah memodifikasi paragraf ini, klik "simpan sementara", dan isi yang dimodifikasi dapat dibaca di halaman "modifikasi dokumen".',
        DocumentTip: 'Fungsi ini dipengaruhi oleh lingkungan sistem. Harap simpan makalah yang dimodifikasi ke makalah Anda sesegera mungkin.',
        AlertSuccess: "Ini adalah isi yang disimpan sementara setelah Anda memodifikasinya di laporan. isi yang diedit akan berhijau",
        SupportBrowser: 'Browser Anda saat ini tidak mendukung modifikasi paragraf, silakan gunakan browser lain!!!',
        FirstPage: "halaman rumah",
        LastPage: "Halaman terakhir",
        PageNumber: "Nomor halaman", 
        Page: "Halaman", 
        NumberOfPages: "Jumlah halaman",
        Loading: "Memuat...", 
        DifferentSimilarityTip: "Warna kalimat yang berbeda menunjukkan kesamaan yang berbeda",
        Red: "Merah",
        Orange: "Jeruk",
        Black: "Hitam",
        Green: "Hijau",
        SevereSimilarity: "Kesamaan lebih dari 70% (tingkat kesamaan tinggi, harap modifikasi secara komprehensif)",
        SlightlySimilar: "Kesamaan 40% - 70% (tingkat kesamaan sedikit, harap modifikasi sesuai kebutuhan)",
        Qualified: "Memenuhi syarat",
        ViewDetailSentence: 'Jika Anda ingin melihat hasil deteksi kalimat terperinci, silakan klik bagian "merah" dan "jeruk" di makalah',
        SentenceSimilarityTip: "Kesamaan kalimat",
        YourSentence: "Kalimat Anda",
        Composite: "Komprehensif",
        Library: "Lokal",
        Internet: "Internet",
        SelfBuiltLibrary: "perpustakaan sendiri",
        SimilarSentences: "Kalimat serupa",
        SimilarOriginalFragment: "Fragmen teks serupa",
        Source: "Sumber",
        Journal: "Jurnal Akademik",
        Dissertation: "Disertasi",
        AcademicConferences: "Konferensi Akademik",
        BookData: "Data buku",
        University: "Database perbandingan bersama mahasiswa",
        Title: "Judul makalah",
        Author: "Penulis",
        Periodical: "Nama jurnal",
        Issue: "Tanggal publikasi",
        PeriodicalColumn: "Kolom jurnal",
        ClassificationNumber: "Nomor klasifikasi",
        Funding: "Proyek Dana",
        Abstract: "Abstrak",
        PublicationDate: "Waktu publikasi",
        PeriodicalLevel: "Tingkat jurnal",
        ISSN: "ISSN",
        DegreeAwarded: "Pengharga",
        DegreeGrantingUnit: "Gelar yang diberikan",
        DegreeYear: "Tahun gelar",
        Major: "Jurusan disiplin",
        TeacherName: "Nama guru",
        Conference: "Nama konferensi",
        Organizer: "Penyelenggara",
        ConferenceDate: "Waktu konferensi",
        ConferenceLocation: "Tempat konferensi",
        Chapter: "Bab",
        Publisher: "Penerbit",
        ISBN: "ISBN",
        Provenance: "Sumber",
        OpenSearch: "OpenSearch",
        Length: "panjang",
        UploadTime: "Waktu unggah",
        Keyword: "Kata kunci",
        BackTop: "Kembali ke atas",
        BasicInformation: "Informasi dasar",
        PaperTitle: "Judul makalah",
        PaperTime: "Waktu makalah",
        LocalLibrarySimilarity: "Kesamaan perpustakaan lokal",
        JournalLibrarySimilarity: "Kesamaan perpustakaan jurnal",
        DegreeLibrarySimilarity: "Kesamaan perpustakaan gelar",
        MeetingSimilarity: "Kesamaan perpustakaan konferensi",
        LibrarySimilarity: "Kesamaan perpustakaan buku",
        InternetSimilarity: "Kesamaan Internet",
        SelfbuiltSimilarity: "Kesamaan perpustakaan sendiri",
        SimilarityCalculationFormula: "Rumus perhitungan kesamaan",
        Formula: "(kesamaan kalimat 1+ kesamaan kalimat 2 +... + kesamaan kalimat n) / n",
        SimilarityRange: "Kisaran kesamaan kalimat adalah 0,0 ~ 1,0",
        SimilarityRangeDetail: "Kesamaan kalimat hijau dihitung sebagai 0",
        SimilarityDistribution: "Distribusi kesamaan kalimat",
        PointDistributionDiagram: "Dagram distribusi titik kalimat yang tidak memenuhi syarat",
        Sentence: "Kalimat",
        LocalLibrariesTitle: "Sumber daya serupa perpustakaan lokal",
        LocalTip: "Tidak ditemukan sumber daya dengan kemiripan tinggi di perpustakaan lokal",
        Details: "Rincian",
        PutAway: "Perkecil",
        ViewMore: "Lihat lainnya",
        InternetSimilarResources: "Sumber daya serupa di Internet",
        InternetTip: "Tidak ditemukan sumber daya dengan kemiripan tinggi di Internet",
        PaperFooter: "Laporan deteksi dihasilkan oleh sistem deteksi kesamaan dokumen PaperPass.Net",
        Copyright: "Hak cipta",
        LoadingOriginal: "Memuat teks asli, harap tunggu",
        Aditional: "Kalimat tambahan",
        Word: "Laporan rinci dengan versi Word",
        Text: "Laporan rinci dengan teks aja",
    },
    "Pilipino": {
        FlagshipVersion: "Ultimate",
        SubmitTime: "Oras ng pasahan",
        PaperNumber: "Bilang ng salita",
        OverallSimilarity: "Kabuuang pagkakatulad",
        DetailReport: "Ulat",
        TextProofreading: "Pagwawasto",
        ComprehensiveAssessment: "Pagtatasa",
        ViewOriginal: "orihinal na teksto",
        UseHelp: "Tulong",
        Download: "Mag-download",
        DownloadOriginal: "I-download ang Orihinal",
        DownloadHTM: "I-download ang Offline na Ulat",
        DownloadPDF: "I-download ang bersyon ng PDF",
        DownloadWord: "I-download ang bersyon ng WORD",
        SupportJavaScript: "Bawal ang Javascript sa browser!!!",
        LoadingReport: "Pakihintay. Naglo-load ang ulat...",
        Similarity: "pagkakatulad",
        SimilarityTip: "Palawakin ang menu sa kanan upang basahin ang detalyadong ulat para sa pangungusap.",
        AditionalSentences: "Karagdagan ng katulad na pangungusap",
        BlankPage: "[Walang laman ang pahinang ito. Pakitingan ang susunod na pahina.]",
        SwitchMode: "Magpalit ng modus",
        DirectoryNavigation: "Talaan ng mga nilalaman",
        WebpageNavigation: "Gabay ng mga pahina",
        ModifyDocument: "Baguhin ang dokumento",
        AuxiliaryLine: "pantulong na salungguhit",
        PreviousPage: "Nakaraang pahina",
        NextPage: "Susunod na pahina",
        Enter: "Ipasok ang numero ng pahina",
        Jump: "Pumunta sa pahina",
        Scale: "Pag-zoom ng pahina",
        Zoom: "Mag-zoom in",
        ZoomOut: "Mag-zoom out",
        ScalingRatio: "Eskala",
        FitWidth: "Umangkop sa lapad",
        SuitableHeight: "Umangkop sa taas",
        OriginalSize: "Ibalik sa orihinal na laki",
        WordMode: 'Sigurado ba kayong nais na ipalit sa modus ng Word?',
        TextMode: 'Sigurado ba kayong nais na ipalit sa modus na may teksto lang?',
        Confirm: "Okey",
        Cancel: "Kanselahin",
        EmptyDirectoryNavigation: "Walang laman ang talaan ng mga nilalaman",
        CollapseAll: "Palawakin lahat",
        ExpandAll: "Pakitidin lahat",
        EmptyWebPageNavigation: "Walang laman ang gabay ng mga pahina",
        UseLine: 'Sigurado ba kayong nais na gamitin ang pantulong na salungguhit?',
        CancelLine: 'Sigurado ba kayong nais na kanselahin ang pantulong na salungguhit?',
        UseAuxiliaryLine: "Gamitin ang pantulong na salungguhit",
        CancelAuxiliaryLine: "Kanselahin ang pantulong na salungguhit",
        ModifyParagraph: "Baguhin ang talata",
        Modify: "Baguhin",
        TemporarySave: "Pansamantalang i-save",
        CancelSave: "Kanselahin ang pag-save",
        ModifyTip: 'Tip: Pagkatapos ng baguhin ang pangungusap nito, i-click ang "Pansamantalang i-save". Maaari ninyong makita ang mga gawang binago sa "Baguhin ang dokumento". ',
        DocumentTip: 'Naaapektuhan ang punsyong ito ng kalagayan ng sistema. Pakisave ang artikulong binago sa tesis ninyo.',
        AlertSuccess: "Nandito ang mga pansamantalang i-save na binago ninyong gawa. Magiging berde ang mga binago.",
        SupportBrowser: 'Hindi sumusuporta sa punsyong "Baguhin ang talata" ang kasalukuyang browser ninyo. Pakigamit ang ibang browser!!!',
        FirstPage: "Unang pahina",
        LastPage: "Huling pahina",
        PageNumber: "Numero ng pahina", 
        Page: "Pahina", 
        NumberOfPages: "Bilang ng pahina",
        Loading: "Naglo-load ...",
        DifferentSimilarityTip: "Ipinapahiwatig ng mga iba't ibang kulay ng mga pangungusap ang iba't ibang antas ng katulad.",
        Red: "Pula",
        Orange: "Kahel",
        Black: "Itim",
        Green: "Berde",
        SevereSimilarity: "Higit sa 70% ang pagkakatulad. (Matindi. Pakibago nang buong-buo.)",
        SlightlySimilar: "40% - 70% ang pagkakatulad. (Banayad. Pakibago kung naaangkop.)",
        Qualified: "Sumusunod sa pamantayan",
        ViewDetailSentence: 'Upang kumuha ng detalyadong mga resulta sa pagsusuri ng pangungusap, paki-click ang bahaging pula at kahel sa artikulo.',
        SentenceSimilarityTip: "Pagkakatulad sa pangungusap nito",
        YourSentence: "Pangungusap ninyo",
        Composite: "Kabuuan",
        Library: "Lokal",
        Internet: "Internet",
        SelfBuiltLibrary: "Sariling database",
        SimilarSentences: "Katulad na pangungusap",
        SimilarOriginalFragment: "Bahagi ng katulad na orihinal na teksto",
        Source: "Pinanggalingan",
        Journal: "Journal",
        Dissertation: "Tesis at disertasyon",
        AcademicConferences: "Proceedings",
        BookData: "Aklat",
        University: "Magkasabay na database ng tesis ng mga estudyante sa unibersidad ng CNKI",
        Title: "Pamagat",
        Author: "May-akda",
        Periodical: "Pamagat ng journal",
        Issue: "Petsa ng paglalathala",
        PeriodicalColumn: "Kolum ng journal",
        ClassificationNumber: "Code ng klasipikasyon",
        Funding: "Pondo",
        Abstract: "Abstrak",
        PublicationDate: "Petsa ng paglalathala",
        PeriodicalLevel: "Grado ng journal",
        ISSN: "ISSN",
        DegreeAwarded: "Digri",
        DegreeGrantingUnit: "Institusyon",
        DegreeYear: "Taon",
        Major: "Mayor",
        TeacherName: "TiyutTaonor",
        Conference: "Pamagat",
        Organizer: "Tagatangkilik",
        ConferenceDate: "Petsa",
        ConferenceLocation: "Sityo",
        Chapter: "Kabanata",
        Publisher: "Palimbagan",
        ISBN: "ISBN",
        Provenance: "Pinanggalingan",
        OpenSearch: "OpenSearch",
        Length: "Haba",
        UploadTime: "Oras",
        Keyword: "Keyword",
        BackTop: "Bumalik sa itaas",
        BasicInformation: "Saligang impormasyon",
        PaperTitle: "Pamagat",
        PaperTime: "Oras",
        LocalLibrarySimilarity: "Pagkakatulad sa database sa lokal",
        JournalLibrarySimilarity: "Pagkakatulad sa database sa journal",
        DegreeLibrarySimilarity: "Pagkakatulad sa database sa tesis at disertasyon",
        MeetingSimilarity: "Pagkakatulad sa database sa proceedings",
        LibrarySimilarity: "Pagkakatulad sa database sa aklat",
        InternetSimilarity: "Pagkakatulad sa database sa internet",
        SelfbuiltSimilarity: "Pagkakatulad sa sariling database",
        SimilarityCalculationFormula: "Pormula para sa pagkakalkula ng pagkakatulad",
        Formula: "(pagkakatulad ng pangungusap 1 +pagkakatulad ng pangungusap 2 + …+pagkakatulad ng pangungusap n)/n",
        SimilarityRange: "0.0-1.0 ang saklaw ng pagkakatulad",
        SimilarityRangeDetail: "0 ang pagkakatulad ng berdeng pangungusap",
        SimilarityDistribution: "Distribusyon ng pagkakatulad ng mga pangungusap",
        PointDistributionDiagram: "Dot plot ng pagkakatulad ng mga pangungusap",
        Sentence: "Pangungusap",
        LocalLibrariesTitle: "Tekstong katulad sa database sa lokal",
        LocalTip: "Walang tekstong katulad ng pangungusap nito na natagpuan sa database sa lokal",
        Details: "Tingnan ang mga detalye",
        PutAway: "Pakitidin lahat",
        ViewMore: "Magpakita ng higit pa",
        InternetSimilarResources: "Tekstong katulad sa internet",
        InternetTip: "Walang tekstong katulad ng pangungusap nito na natagpuan sa database sa internet",
        PaperFooter: "Nabubuo ang ulat gamit sa sistemang pagsusuri ng pagkakatulad ng mga dokumento ng PaperPass.Net",
        Copyright: "Kopirayt",
        LoadingOriginal: "Pakihintay. Naglo-load ang orihinal na teksto...",
        Aditional: "Karagdagang pangungusap",
        Word: "Detalyadong ulat(Word)",
        Text: "Detalyadong ulat(teksto lang)",
    },
    "हिंदी": {
        FlagshipVersion: "सर्वश्रेष्ठ संस्करण ",
        SubmitTime: "प्रस्तुत करने का समय",
        PaperNumber: "वर्णों की संख्या",
        OverallSimilarity: "समग्र समानता",
        DetailReport: "रिपोर्ट",
        TextProofreading: "प्रूफरीडर",
        ComprehensiveAssessment: "मूल्यांकन",
        ViewOriginal: "मूल पाठ",
        UseHelp: "सहायता",
        Download: "डाउनलोड",
        DownloadOriginal: "मूल डाउनलोड करें",
        DownloadHTM: "ऑफलाइन रिपोर्ट डाउनलोड करें",
        DownloadPDF: "पीडीएफ संस्करण डाउनलोड करें",
        DownloadWord: "वर्ड वर्जन डाउनलोड करें",
        SupportJavaScript: "आपका ब्राउज़र Javascript अक्षम है!!!",
        LoadingReport: "रिपोर्ट लोड हो रहा है,कृपया प्रतीक्षा करें...",
        Similarity: "समानता",
        SimilarityTip: "वाक्य की विस्तृत रिपोर्ट देखने के लिए, कृपया दाईं ओर की विस्तार करें!",
        AditionalSentences: "समान वाक्य अनुपूरक पेज",
        BlankPage: "[यह पेज खाली है, कृपया अगले पेज देखें]",
        SwitchMode: "मोड बदलें",
        DirectoryNavigation: "सूची नेविगेशन",
        WebpageNavigation: "पेज नेविगेशन",
        ModifyDocument: "दस्तावेज़ को संशोधित करें",
        AuxiliaryLine: "सहायक लाइन",
        PreviousPage: "पिछला पेज",
        NextPage: "अगला पेज",
        Enter: "पेज नंबर दर्ज करें",
        Jump: "छलांग",
        Scale: "ज़ूम",
        Zoom: "विस्तार करें",
        ZoomOut: "ज़ूम आउट करें",
        ScalingRatio: "स्केलिंग अनुपात",
        FitWidth: "अनुकूल चौड़ाई",
        SuitableHeight: "अनुकूल लम्बाई",
        OriginalSize: "मूल आकार",
        WordMode: 'क्या आप "वर्ड कोड" पर स्विच करना चाहते हैं?',
        TextMode: 'क्या आप "टेक्स्ट कोड" पर स्विच करना चाहते हैं?',
        Confirm: "पुष्टि करें",
        Cancel: "रद्द करें",
        EmptyDirectoryNavigation: "सूची नेविगेशन खाली है",
        CollapseAll: "सब विस्तार करें",
        ExpandAll: "सब छुपा करें",
        EmptyWebPageNavigation: "पेज नेविगेशन खाली है",
        UseLine: '"सहायक लाइन का उपयोग" करने की पुष्टि करें?',
        CancelLine: '"सहायक लाइन को रद्द" करने की पुष्टि करें?',
        UseAuxiliaryLine: "सहायक लाइन का उपयोग करें",
        CancelAuxiliaryLine: "सहायक लाइन को रद्द करें",
        ModifyParagraph: "पैराग्राफ संशोधन",
        Modify: "संशोधन",
        TemporarySave: "अस्थायी बचत करें",
        CancelSave: "बचत रद्द करें",
        ModifyTip: 'नोट: इस पैराग्राफ को संशोधन करने के बाद "अस्थायी बचत करें" को क्लिक करें,फिर "संशोधित दस्तावेज़" पेज में देखा जा सकता है|',
        DocumentTip: 'यह भूमिका सिस्टम के वातावरण से प्रभावित होता है,कृपया पाठ को जल्दी अपने पेपर में सहेजें|',
        AlertSuccess: "यह रिपोर्ट को संशोधित करने के बाद अस्थायी सहेजी गई सामग्री है, संपादित सामग्री हरी हो जाएगी",
        SupportBrowser: 'आपका ब्राउज़र पैरा संपादन का समर्थन नहीं करता, किसी अन्य ब्राउज़र का उपयोग करें! ! !',
        FirstPage: "फ्रंट पेच",
        LastPage: "अंतिम पेज",
        PageNumber: "पेज नंबर", 
        Page: "पेज", 
        NumberOfPages: "पेज की संख्या",
        Loading: "लोड हो रहा है...",
        DifferentSimilarityTip: "वाक्यों के अलग-अलग रंग मतलब है कि अलग-अलग समानता डिग्री",
        Red: "लाल",
        Orange: "नारंगी",
        Black: "काला",
        Green: "हरा",
        SevereSimilarity: "समानता 70% से अधिक है (बहुत समान, कृपया इसे पूरी तरह से संशोधित करें)",
        SlightlySimilar: "समानता 40% -70% (थोड़ा समान, कृपया ज़रा संशोधित करें)",
        Qualified: "योग्य",
        ViewDetailSentence: 'अगर आप ववाक्यों के विस्तृत परीक्षा परिणाम देखना चाहते हैं,कृपया पेपर में "लाल" और "नारंगी" चिह्नित भागों पर क्लिक करें। ',
        SentenceSimilarityTip: "इस वाक्य की समानता किग्री",
        YourSentence: "आप की वाक्य",
        Composite: "व्यापक",
        Library: "स्थानीय",
        Internet: "इंटरनेट",
        SelfBuiltLibrary: "स्वयं निर्मित डेटाबेस",
        SimilarSentences: "समान वाक्य",
        SimilarOriginalFragment: "सामान्य मूल पाठ",
        Source: "स्रोत",
        Journal: "अकादमिक पत्रिका",
        Dissertation: "स्नातक थीसिस",
        AcademicConferences: "अकादमिक मंच",
        BookData: "पुस्तक डेटा",
        University: "विश्वविद्यालय संघ डेटाबेस",
        Title: "शीर्षक",
        Author: "लेखक",
        Periodical: "पत्रिका नाम",
        Issue: "प्रकाशन तिथि",
        PeriodicalColumn: "पत्रिका कालम",
        ClassificationNumber: "वर्गीकरण कोड",
        Funding: "फंड परियोजना",
        Abstract: "सारांश",
        PublicationDate: "प्रकाशन की तारीख",
        PeriodicalLevel: "पत्रिका स्तर",
        ISSN: "आई.एस.एस.एन.",
        DegreeAwarded: "प्रदान संस्था",
        DegreeGrantingUnit: "डिग्री प्रदान",
        DegreeYear: "डिग्री वर्ष",
        Major: "विशिष्ट विषय",
        TeacherName: "शिक्षक का नाम",
        Conference: "मंच का नाम",
        Organizer: "आयोजक",
        ConferenceDate: "मंच का समय",
        ConferenceLocation: "मंच की जगह",
        Chapter: "अध्याय",
        Publisher: "प्रकाशन संस्था",
        ISBN: "आई.एस.बी.एन.",
        Provenance: "उद्गम",
        OpenSearch: "ओपन सर्च",
        Length: "वर्णों की संख्या",
        UploadTime: "अपलोड समय",
        Keyword: "कुंजी शब्द",
        BackTop: "शीर्ष पर वापस जाएँ",
        BasicInformation: "बुनियादी जानकारी",
        PaperTitle: "पेपर विषय",
        PaperTime: "पेपर का समय",
        LocalLibrarySimilarity: "स्थानीय संग्रहीत डेटाबेस समानता",
        JournalLibrarySimilarity: "पत्रिका डेटाबेस समानता",
        DegreeLibrarySimilarity: "स्नातक थीसिस डेटाबेस समानता",
        MeetingSimilarity: "मंच पेपर डेटाबेस समानता",
        LibrarySimilarity: "पुस्तकार डेटाबेस समानता",
        InternetSimilarity: "इंटरनेट डेटाबेस समानता",
        SelfbuiltSimilarity: "स्वयं निर्मित डेटाबेस समानता",
        SimilarityCalculationFormula: "समानता गणना सूत्र",
        Formula: "(वाक्य १ समानता + वाक्य २ समानता +…+वाक्य n समानता) / n",
        SimilarityRange: "वाक्य समानता रेंज 0.0～1.0",
        SimilarityRangeDetail: "हरे रंग की वाक्य समानता की डिग्री 0 है",
        SimilarityDistribution: "वाक्य समानता वितरण",
        PointDistributionDiagram: "अयोग्य वाक्यों का बिंदु वितरण आरेख",
        Sentence: "वाक्य",
        LocalLibrariesTitle: "स्थानीय डेटाबेस समान सामग्री",
        LocalTip: "स्थानीय डेटाबेस से समान सामग्री नहीं मिला",
        Details: "विवरण",
        PutAway: "छपा करें",
        ViewMore: "और अधिक देखें",
        InternetSimilarResources: "इंटरनेट डेटाबेस से समान सामग्री",
        InternetTip: "कोई इंटरनेट डेटाबेस से समान सामग्री नहीं मिला ",
        PaperFooter: "निरीक्षण रिपोर्ट पपेर्पास दस्तावेज़ समानता निरीक्षण प्रणाली से उत्पन्न होती है",
        Copyright: "कॉपीराइट",
        LoadingOriginal: "मूल पाठ लोड हो रहा है, कृपया प्रतीक्षा करें...",
        Aditional: "पूरक वाक्य",
        Word: "विस्तृत रिपोर्ट। वर्ड संस्करण",
        Text: "विस्तृत रिपोर्ट। पाठ संस्करण",
    },
    "বাংলা": {
        FlagshipVersion: "ফ্ল্যাগশিপ সংস্করণ",
        SubmitTime: "জমা দেওয়ার সময়",
        PaperNumber: "শব্দ গণনা",
        OverallSimilarity: "সামগ্রিক মিল",
        DetailReport: "রিপোর্ট",
        TextProofreading: "প্রুফ রিডিং",
        ComprehensiveAssessment: "মূল্যায়ন",
        ViewOriginal: "মূল",
        UseHelp: "সাহায্য",
        Download: "ডাউনলোড করুন",
        DownloadOriginal: "অরিজিনাল ডাউনলোড করুন",
        DownloadHTM: "অফলাইন রিপোর্ট ডাউনলোড করুন",
        DownloadPDF: "পিডিএফ ভার্সন ডাউনলোড করুন",
        DownloadWord: "WORD সংস্করণ ডাউনলোড করুন",
        SupportJavaScript: "আপনার বর্তমান ব্রাউজার জাভাস্ক্রিপ্ট নিষ্ক্রিয় !!",
        LoadingReport: "রিপোর্ট লোড হচ্ছে, অনুগ্রহ করে অপেক্ষা করুন ...",
        Similarity: "মিল",
        SimilarityTip: "বাক্যের বিস্তারিত প্রতিবেদন দেখতে, দয়া করে ডান দিকটি প্রসারিত করুন!",
        AditionalSentences: "অনুরূপ বাক্যের জন্য পরিপূরক পৃষ্ঠা",
        BlankPage: "[এই পৃষ্ঠাটি ফাঁকা, অনুগ্রহ করে পরবর্তী পৃষ্ঠা দেখুন]",
        SwitchMode: "সুইচ মোড",
        DirectoryNavigation: "ডিরেক্টরি নেভিগেশন",
        WebpageNavigation: "পৃষ্ঠা নেভিগেশন",
        ModifyDocument: "নথি আপডেট করুন",
        AuxiliaryLine: "সহায়ক লাইন",
        PreviousPage: "শেষ পৃষ্ঠা",
        NextPage: "পরবর্তী পৃষ্ঠা",
        Enter: "পৃষ্ঠা নম্বর লিখুন",
        Jump: "যাও",
        Scale: "জুম",
        Zoom: "প্রসারিত করো",
        ZoomOut: "ছোট করা",
        ScalingRatio: "স্কেল",
        FitWidth: "ফিট প্রস্থ",
        SuitableHeight: "উপযুক্ত উচ্চতা",
        OriginalSize: "মূল আকার",
        WordMode: '"ওয়ার্ড মোড" এ যান?',
        TextMode: '"শুধুমাত্র পাঠ্য মোডে" স্যুইচ করবেন?',
        Confirm: "ইয়েস",
        Cancel: "বাতিল করুন",
        EmptyDirectoryNavigation: "ডিরেক্টরি নেভিগেশন খালি",
        CollapseAll: "পৃষ্ঠাটি প্রসারিত করুন",
        ExpandAll: "পাতা ভাঁজ করুন",
        EmptyWebPageNavigation: "পৃষ্ঠা নেভিগেশন ফাঁকা",
        UseLine: '"অক্জিলিয়ারী লাইন ব্যবহার করতে"?',
        CancelLine: '"অক্জিলিয়ারী লাইন অপসারণ" করতে?',
        UseAuxiliaryLine: "সহায়ক লাইন ব্যবহার করুন",
        CancelAuxiliaryLine: "অক্জিলিয়ারী লাইন বাতিল করুন",
        ModifyParagraph: "অনুচ্ছেদ পরিবর্তন",
        Modify: "সংশোধন",
        TemporarySave: "সাময়িক সংরক্ষণ",
        CancelSave: "সংরক্ষণ বাতিল করুন",
        ModifyTip: 'দ্রষ্টব্য: এই অনুচ্ছেদটি সংশোধন করার পরে, "সাময়িকভাবে সংরক্ষণ করুন" এ ক্লিক করুন। পরিবর্তিত বিষয়বস্তু "নথি পরিবর্তন করুন" পৃষ্ঠায় দেখা যাবে।',
        DocumentTip: 'এই ফাংশনটি সিস্টেম পরিবেশ দ্বারা প্রভাবিত হয়, অনুগ্রহ করে যত তাড়াতাড়ি সম্ভব সংশোধিত নিবন্ধটি আপনার কাগজে সংরক্ষণ করুন।',
        AlertSuccess: "এই সামগ্রীটি সাময়িকভাবে সংরক্ষণ করা হয়েছে আপনি প্রতিবেদনটি সংশোধন করার পরে, সম্পাদিত সামগ্রী সবুজ হয়ে যাবে",
        SupportBrowser: 'আপনার বর্তমান ব্রাউজার অনুচ্ছেদ সম্পাদনা সমর্থন করে না, দয়া করে অন্য ব্রাউজার ব্যবহার করুন! ! !',
        FirstPage: "হোমপেজ",
        LastPage: "শেষ পৃষ্ঠা",
        PageNumber: "পৃষ্ঠা সংখ্যা", 
        Page: "পৃষ্ঠা", 
        NumberOfPages: "পৃষ্ঠা সংখ্যা",
        Loading: "লোড হচ্ছে ...",
        DifferentSimilarityTip: "বাক্যের বিভিন্ন রং বিভিন্ন ধরনের মিলের ইঙ্গিত দেয়",
        Red: "লাল",
        Orange: "কমলা",
        Black: "কালো",
        Green: "সবুজ",
        SevereSimilarity: "৭০% এর বেশি মিল (গুরুতর মিল, দয়া করে সম্পূর্ণ পরিবর্তন করুন) ",
        SlightlySimilar: "4০% -৭০% মিল (হালকা মিল, অনুগ্রহ করে যথাযথভাবে সংশোধন করুন) ",
        Qualified: "গুণসম্পন্ন",
        ViewDetailSentence: 'বাক্যের বিস্তারিত শনাক্তকরণের ফলাফলের জন্য, দয়া করে কাগজে "লাল" এবং "কমলা" চিহ্নিত অংশগুলিতে ক্লিক করুন',
        SentenceSimilarityTip: "এই বাক্যের মিল",
        YourSentence: "আপনার বাক্য",
        Composite: "ব্যাপক",
        Library: "স্থানীয়",
        Internet: "ইন্টারনেট",
        SelfBuiltLibrary: "স্ব-নির্মিত ডাটাবেস",
        SimilarSentences: "অনুরূপ বাক্য",
        SimilarOriginalFragment: "অনুরূপ মূল টুকরা",
        Source: "সূত্র",
        Journal: "একাডেমিক জার্নাল",
        Dissertation: "একাডেমিক গবেষণাপত্র",
        AcademicConferences: "একাডেমিক সম্মেলন",
        BookData: "বইয়ের তথ্য",
        University: "স্নাতক থিসিসের যৌথ তুলনা ডাটাবেস",
        Title: "টাইটেল",
        Author: "লেখক",
        Periodical: "জার্নালের নাম",
        Issue: "প্রকাশনার তারিখ",
        PeriodicalColumn: "জার্নাল কলাম",
        ClassificationNumber: "শ্রেণীবিভাগ নং",
        Funding: "তহবিল প্রোগ্রাম",
        Abstract: "সারাংশ",
        PublicationDate: "প্রকাশনার সময়",
        PeriodicalLevel: "জার্নাল স্তর",
        ISSN: "আইএসএসএন",
        DegreeAwarded: "মঞ্জুরি কর্তৃপক্ষ",
        DegreeGrantingUnit: "ডিগ্রী মঞ্জুর",
        DegreeYear: "ডিগ্রির বছর",
        Major: "বিভাগ এবং বিশেষত্ব",
        TeacherName: "তত্ত্বাবধায়ক",
        Conference: "সম্মেলনের নাম",
        Organizer: "স্পনসর",
        ConferenceDate: "সম্মেলনের সময়",
        ConferenceLocation: "সম্মেলনের অবস্থান",
        Chapter: "অধ্যায় এবং বিভাগ",
        Publisher: "প্রকাশনা ঘর",
        ISBN: "আইএসবিএন",
        Provenance: "উৎপত্তি",
        OpenSearch: "খোলা অনুসন্ধান",
        Length: "দৈর্ঘ্য",
        UploadTime: "আপলোড করার সময়",
        Keyword: "মূল শব্দ",
        BackTop: "উপরে ফিরে যাও",
        BasicInformation: "মৌলিক তথ্য",
        PaperTitle: "থিসিস শিরোনাম",
        PaperTime: "থিসিসের সময়",
        LocalLibrarySimilarity: "স্থানীয় ডাটাবেসের সাথে মিল",
        JournalLibrarySimilarity: "জার্নাল ডাটাবেসের সাথে মিল",
        DegreeLibrarySimilarity: "গবেষণামূলক ডাটাবেসের সাথে মিল",
        MeetingSimilarity: "কনফারেন্স ডাটাবেসের সাথে মিল",
        LibrarySimilarity: "বইয়ের ডাটাবেসের সাথে মিল",
        InternetSimilarity: "ইন্টারনেট  রিসোর্সের  সম্পদের সাথে মিল",
        SelfbuiltSimilarity: "স্ব-নির্মিত ডাটাবেসের সাথে মিল",
        SimilarityCalculationFormula: "মিলের গণনার সূত্র",
        Formula: "(বাক্য ১ এর মিল + বাক্য ২ এর মিল ... + + বাক্য n এর মিল)",
        SimilarityRange: "বাক্যের মিল 0.0 থেকে ১.0 পর্যন্ত ",
        SimilarityRangeDetail: "সবুজ বাক্যের মিল 0 হিসাবে গণনা করা হয় ",
        SimilarityDistribution: "বাক্যের মিলের বন্টন",
        PointDistributionDiagram: "অযোগ্য বাক্যের ডট বিতরণ",
        Sentence: "বাক্য",
        LocalLibrariesTitle: "স্থানীয় ডাটাবেসের অনুরূপ রিসোর্স",
        LocalTip: "স্থানীয় ডাটাবেসের অনুরূপ কোন রিসোর্স নেই",
        Details: "বিস্তারিত",
        PutAway: "ভাঁজ করা",
        ViewMore: "আরো দেখুন",
        InternetSimilarResources: "ইন্টারনেটের অনুরূপ রিসোর্স",
        InternetTip: "ইন্টারনেটের অনুরূপ কোন রিসোর্সনেই",
        PaperFooter: "সনাক্তকরণ প্রতিবেদনটি পেপারপাসের সাহিত্য সাদৃশ্য সনাক্তকরণ পদ্ধতি দ্বারা তৈরি করা হয়।",
        Copyright: "কপিরাইট",
        LoadingOriginal: "মূল লেখাটি লোড হচ্ছে, অনুগ্রহ করে অপেক্ষা করুন ...",
        Aditional: "পরিপূরক বাক্য ",
        Word: "বিস্তারিত প্রতিবেদন. শব্দ সংস্করণ",
        Text: "বিস্তারিত প্রতিবেদন. শুধুমাত্র পাঠ্য সংস্করণ", 
    }
}